context:
  version: "3.3.10"

package:
  name: riff
  version: ${{ version }}

source:
  url: https://github.com/walles/riff/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6db6ac7525f00c4a4cb45351b9a229e253b3e9053ab365d6f881c0144159f8da

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo install --no-track --locked --root ${PREFIX} --path .
          - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      - if: win
        then:
          - cargo install --no-track --locked --root %PREFIX% --path .
          - if errorlevel 1 exit 1
          - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
          - if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - riff --help

about:
  homepage: https://github.com/walles/riff
  repository: https://github.com/walles/riff
  documentation: https://github.com/walles/riff
  summary: A diff filter highlighting which line parts have changed
  description: |
    Riff is a wrapper around diff that highlights which parts of lines have
    changed.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
